# Generated by Django 5.2.3 on 2025-06-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('R', 'ROMANCE'), ('C', 'COMEDY'), ('P', 'POLITICS'), ('F', 'FICTION')], default='C', max_length=1, unique=True),
        ),
    ]
