# Generated by Django 5.2.3 on 2025-06-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_language_name_alter_bookinstance_status'),
        ('user', '0003_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='user.author'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
