# Generated by Django 5.2.4 on 2025-07-07 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_bookimage_book_alter_bookimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='comments',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='author',
            name='phone',
        ),
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('A', 'AVAILABLE'), ('B', 'BORROWED'), ('M', 'MAINTENANCE')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('R', 'ROMANCE'), ('C', 'COMEDY'), ('P', 'POLITICS'), ('F', 'FICTION')], default='C', max_length=1, unique=True),
        ),
    ]
