# Generated by Django 5.2.4 on 2025-07-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_comments_bookinstance_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='book-images-details'),
        ),
    ]
