# Generated by Django 5.2.4 on 2025-07-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
