# Generated by Django 5.2.3 on 2025-07-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_author_alter_book_author'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
